config/routes.rb
Rails.application.routes.draw do
  resources :tickets

  devise_for :users
  
  devise_scope :user do
    get '/' => 'devise/sessions#new'
  end
  
  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :created_by, :class_name => :User
end

app/models/ticket_reply.rb
class TicketReply < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :created_by, :class_name => :User
end

app/models/ticket_user_up_votes.rb
class TicketUserUpVotes < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
  
  def after_sign_in_path_for( user )
    '/tickets'
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
    @new_ticket = Ticket.new
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    @ticket.created_by = current_user
    @ticket.created_at = DateTime.now
    
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:id, :title, :description, :estimated_delivery, :status, :jira_ticket_number, :created_at, :created_by_id, :active, :epic)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  module BootstrapExtension
  
    def form_for( resource, options = {} )
      add_form_control_to options
      super
    end
    
    def text_area( resource, column, options = {} )
      add_form_control_to options
      super
    end
    
    def text_field( resource, column, options = {} )
      add_form_control_to options
      super
    end
    
    def text_field_tag( name, options = {} )
      add_form_control_to options
      super
    end
    
    def primary_button( text, options = {} )
      cls = options[ :class ]
      if cls.nil?
        cls = 'class="btn btn-primary"'
      else
        cls = 'class="' + cls + ' btn btn-primary"'
      end
      
      
      "<button #{cls}>#{html_escape text}</button>".html_safe
    end
    
    private
    
    def add_form_control_to( options )
      if options[ :class ].nil?
        options[ :class ] = 'form-control'
      else
        options[ :class ] << ' form-control'
      end
    end
  end
  
  include BootstrapExtension
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicketRequestForum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="flash-messages">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/tickets/_form.html.erb
<%= form_for( @ticket, class: 'form' ) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <button class="btn btn-primary">Create Ticket</button>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<h1>Feature Request Voting System</h1>
<div class="row">
  <div class="col-md-12">
    Below you will find the most requested features, and the ability to add different features.
    There are a couple of filters that can be used to see different items. You can sort only by 2
    types, most voted and most recently asked.
  </div>
</div>

<br/>

<div class="row">
  <div class="col-md-12">
    4 comments have been added to features you requested.
  </div>
</div>
<br/>

<%# Filtering and sorting %>

<div clas="row">
  <div class="col-md-12">
    <div class="pull-left">
      <div>Filter By: </div>
      <span class="btn btn-link">Valid</span>
      <span class="btn btn-link" disabled="disabled">Tickets Requested By Me</span>
      <span class="btn btn-link">Completed / Rejected</span>
    </div>
    
    <div class="pull-right">
      <div>Sort By: </div>
      <span class="btn btn-link" disabled="disabled">Most Voted</span>
      <span class="btn btn-link">Most Recent</span>
    </div>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-md-12">
    <span class="btn btn-link new-ticket-link">Request New Feature</span>
  </div>
  <div class="col-md-11 col-md-offset-1 hidden new-ticket-container">
    <%= form_for @new_ticket do |f| %>
      <div class="form-group">
        <%= label_tag :title, 'Title: ' %>
        <%= text_field :ticket, :title %>
      </div>
      
      <div class="form-group">
        <%= label_tag :description, 'Description: ' %>
        <%= text_area :ticket, :description %>
      </div>
      
      <div class="form-group">
        <%= primary_button 'Add Ticket' %>
      </div>
    <% end %>
  </div>
</div>

<% @tickets.each do |ticket| %>
  <div class="row ticket-container" data-ticket-id="<%= ticket.id %>">
    <div class="col-md-1 ticket-vote-container">
      <span>0 Votes</span>
      <button class="btn">Vote</button> <%# If the user has already voted, this should say unvote. %>
    </div>
    <div class="col-md-11">
      <h3><%= link_to( ticket.title, ticket_path( ticket ) ) %></h3>
      <div class="row">
        <div class="col-md-9">
          <%= ticket.description %>
        </div>
        <div class="col-md-2">
          <div>Created By: <%= ticket.created_by and ticket.created_by.email %></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-11">
          <span class="btn btn-link comment">0 comments</span>
        </div>
      </div>
    </div>
  </div>
<% end %>

<br/>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @ticket.id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<p>
  <strong>Estimated delivery:</strong>
  <%= @ticket.estimated_delivery %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<p>
  <strong>Jira ticket number:</strong>
  <%= @ticket.jira_ticket_number %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @ticket.created_at %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @ticket.created_by %>
</p>

<p>
  <strong>Active:</strong>
  <%= @ticket.active %>
</p>

<p>
  <strong>Epic:</strong>
  <%= @ticket.epic %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>m2M Strategies Ticket Request System</h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <p>
      Log in to see the different features that are being requested.
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="box">
      <form class="form" action="/users/sign_in" method="post">
        <div class="form-group">
          <label for="user_email">Email </label>
          <input type="text" class="form-control" id="user_email" name="user[email]"></input>
        </div>
        
        <div class="form-group">
          <label for="user_password">Password </label>
          <input type="password" class="form-control" id="user_password" name="user[password]"></input>
        </div>
        
        <div class="form-group">
          <button class="btn btn-primary pull-right">Login</button>
        </div>
      </form>
    </div>
  </div>
</div>